Release SciBib version 2
UKN-DBVIS/SciBib pull request #33
Opened 2020-09-18 15:01 UTC by benibaeumle

2020-09-22 13:21 UTC, eren-ck requested changes
Please add a License file and simplify the readme.md file. Add ab example figure and link to the scibib pape as a demo page. 

* Why does the `requirements.txt` does not include the lib versions? 
* Remove commented snippets e.g., in `app/backend/db_controller/db.py`
* Is the code secured against SQL injections? 
* Add comments to each method and file. 
* Fix all todos in your code 

Cheers, 
Eren

2020-09-24 15:19 UTC, benibaeumle commented
I worked through most of the requested changes:

* added versions in requirements.txt
* removed commented snippets from files
* all SQLAlchemy queries and execute statements are implemented as recommended by the docs (https://docs.sqlalchemy.org/en/13/). Nevertheless, the docs do not explicitly state to be secured against SQL injections
* each code snippet has been commented
* ToDOs are fixed
* I checked against the libraries and frameworks used and removed incompatible libraries. All remaining libs are compatible with the GPLv3 license, which I added to the new SciBib version. **Note**: Version 1 was published with Apache 2.0 license

The only remaining issue is to simplify the readme. But I am not sure what this means or how to do it.

2020-09-25 11:56 UTC, benibaeumle commented
All requested changes are implemented now.

2020-09-28 07:35 UTC, eren-ck approved these changes

2020-09-28 07:36 UTC, merged